version: "3"

services:
  minecraft:
    image: itzg/minecraft-server:latest
    ports:
      - "25595:25565"
    volumes:
      - "./:/data"
    environment:
      EULA: "TRUE"
      GAMEMODE: survival
      DIFFICULTY: hard
      VERSION: 1.20.1
      MEMORY: 8G
      ICON: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTz8Q3AakCfaC4YA1KpWMTyflfiwSJzTkyFsjWCX2JaKTnb6CUt4HjNFJgv3bkApOFc5P>
      MOTD: "§q§lChimney man's Steamcraft computer box"
      TYPE: AUTO_CURSEFORGE
      # allocate from https://console.curseforge.com/ and set in .env file
      CF_API_KEY: ${CF_API_KEY}
      CF_SLUG: jaffa-factory-2-replica
      VIEW_DISTANCE: 12
    restart: always

volumes:
  mc: {}