version: '3'

services:
  minecraft:
    image: itzg/minecraft-server:latest
    ports:
      - "25565:25565"
    volumes:
      - "./:/data"
    environment:
      EULA: "TRUE"
      GAMEMODE: survival
      DIFFICULTY: hard
      VERSION: latest
      MEMORY: 4G
      ICON: "https://avatars.githubusercontent.com/u/43029469?v=4"
      MOTD: "§q§lGerrudo's §kMinecraft §rServer"
    restart: always

volumes:
  mc: {}
