  
version: "3"

services:
  mc:
    image: itzg/minecraft-server:java8-multiarch
    ports:
      - 25555:25565
    environment:
      EULA: "TRUE"
      TYPE: "CUSTOM"
      CUSTOM_SERVER: "Tekkit.jar"
      DISABLE_HEALTHCHECK: "TRUE"
    volumes:
      # attach the relative directory 'data' to the container's /data path
      [/home/tom/docker/tekkitclassic:/data]
